export const forms = [
  { id: 'react', name: 'React.js', logo: '/logos/react.svg', discipline: 'Frontend engineering', shortLabel: 'Frontend', color: '#61dafb', ink: '#172329', soft: '#e5f9ff', headline: 'Interfaces that work as good as they feel.', description: 'Scalable React architecture, thoughtful interactions, and independent teams. I build the foundations that let great digital experiences grow.', skills: ['React', 'TypeScript', 'Module Federation', 'HTML & CSS', 'SASS', 'Material UI', 'WCAG'], metric: '80', metricSuffix: '%', result: 'fewer deployment dependencies', evidence: 'Led a Module Federation micro-frontend transformation, enabling independent releases and parallel development.' },
  { id: 'graphql', name: 'GraphQL', logo: '/logos/graphql.svg', discipline: 'Backend & APIs', shortLabel: 'Backend', color: '#e10098', ink: '#ffffff', soft: '#fce5f5', headline: 'Complex systems. Clear connections.', description: 'Behind every effortless interaction is a well-engineered system. I connect robust APIs and efficient queries to responsive, dependable products.', skills: ['GraphQL', 'REST APIs', '.NET', 'Python', 'Query caching', 'System design'], metric: '25', metricSuffix: '%', result: 'lower API latency', evidence: 'Improved GraphQL query caching and schemas, lifting Apdex scores from 0.49 to 0.72.' },
  { id: 'aws', name: 'AWS', logo: '/logos/aws.svg', discipline: 'Cloud & data', shortLabel: 'Cloud & data', color: '#ff9900', ink: '#222720', soft: '#fff2dc', headline: 'Big data. Smaller overhead.', description: 'Reliable pipelines and deliberate cloud choices. I turn high-volume data into useful information while keeping complexity and costs in check.', skills: ['AWS Lambda', 'AWS Glue', 'DynamoDB', 'ETL pipelines', 'Cloud optimization', 'CI/CD'], metric: '5', metricSuffix: 'min', result: 'average ETL pipeline runtime', evidence: 'Built an AWS Glue pipeline to load high-volume datasets into DynamoDB, and retired underutilized cloud jobs.' },
  { id: 'python', name: 'Python', logo: '/logos/python.svg', discipline: 'Automation & tooling', shortLabel: 'Automation', color: '#3776ab', ink: '#ffffff', soft: '#e8f2fb', headline: 'Less busywork. More building.', description: 'Python is part of my full-stack toolkit, alongside data validation, ETL pipelines, and developer tooling that makes everyday engineering work easier.', skills: ['Python', 'Great Expectations', 'AWS Glue', 'ETL pipelines', 'Developer tooling', 'AI-assisted development'], metric: '35', metricSuffix: '%', result: 'more efficient developer workflows', evidence: 'Developed internal tooling that streamlined local debugging and frontend unit testing workflows by 35%.' },
  { id: 'dotnet', name: '.NET', logo: '/logos/dotnet.svg', discipline: 'Backend engineering', shortLabel: 'Backend', color: '#512bd4', ink: '#ffffff', soft: '#eee9fc', headline: 'Dependable foundations for complex products.', description: '.NET is part of my backend toolkit, connecting enterprise interfaces to REST APIs and carefully designed services.', skills: ['.NET', 'REST APIs', 'System design', 'TDD', 'CI/CD', 'Performance optimization'], metric: 'REST', metricSuffix: '', result: 'API engineering', evidence: 'Built robust REST endpoints for high-throughput traffic as part of my full-stack work at Thoughtworks.' },
]

export const experience = [
  { title: 'Application Developer - Senior Consultant', dates: 'JUN 2025 - PRESENT', achievements: ['Led a micro-frontend transformation with Module Federation, reducing cross-team deployment dependencies by 80%.', 'Guided React 16 to 18 and Enzyme to RTL migrations, expanding automated test coverage by 25%.', 'Built interactive analytics dashboards for real-time lead prioritization and improved Apdex from 0.49 to 0.72.', 'Mentored engineers on TDD, resolved 15+ skipped UI tests, and automated workflows to reduce manual overhead by 35%.'] },
  { title: 'Application Developer - Consultant', dates: 'AUG 2021 - JUN 2025', achievements: ['Engineered GraphQL queries and REST endpoints for high-throughput traffic, lowering response times by 25%.', 'Automated data validation with Great Expectations, reducing production data issues by 30% and saving 15 hours per week.', 'Built AWS Glue to DynamoDB pipelines with a 5-minute average runtime and Selenium user journeys completing in under 30 minutes.'] },
  { title: 'Application Developer Intern', dates: 'MAR 2021 - JUL 2021', achievements: ['Practiced Agile pair programming with senior engineers, contributing to a 25% reduction in team codebase defects.', 'Built automated unit tests and contributed production code using clean code and CI/CD practices.'] },
]